### PR TITLE
Add portability/integration testing with Sage

### PR DESCRIPTION
**Pull request by mkoeppe**

### CODE REVIEW

**Comment by dimpase** [comment]
I presume this only starts making sense once the necessary changes are done in Sage, right?

**Comment by mkoeppe** [comment]
Next steps:
1) Put a version on PyPI
2) https://trac.sagemath.org/ticket/32894#comment:11
3) Merge this PR.

**Comment by mkoeppe** [comment]
0.Get rid of `lib_path='/home/dimpase/tmp/lib'` and rpath settings in your setup.py. It's the responsibility of the user who calls setup.py to set CFLAGS, LDFLAGS etc.

**Comment by dimpase** [comment]
> 0.Get rid of `lib_path='/home/dimpase/tmp/lib'`

this is on https://github.com/dimpase/primecountpy/#todo

Haven't yet decided whether this should eventually be in `setup.cfg`, or passed in `pip` call.
(In case of out of Sage tree building, this might be tricky.)

What's wrong with keeping rpath settings? They work, in all settings I tried.

**Comment by mkoeppe** [comment]
> whether this should eventually be in `setup.cfg`

That's an outdated approach that no longer makes sense given that people install using pip from PyPI or URLs.

**Comment by mkoeppe** [comment]
Just delete this stuff, then this is ready for PyPI

**Comment by dimpase** [comment]
without lib_path I can't do rpath, and I need it if my libraries are in a non-standard location; e.g.  if I remove `extra_link_args=['-Wl,-rpath,'+lib_path],` I get a complete fail from pytest:
```
...
E   ImportError: libprimecount.so.7: cannot open shared object file: No such file or directory
...
```

**Comment by mkoeppe** [comment]
Put it in your README to use `export LDFLAGS=....`, don't put stuff like this in setup.py

**Comment by dimpase** [comment]
I have found that I can replace `lib_path`-related values in setup.py with command line options while running `build_ext`, liek this:
```
export WDIR=<...>
python3 setup.py build_ext --inplace --rpath=$WDIR --library-dirs=$WDIR
```
The result passes tests with pytest. But I can't do the same for installing:
```
python3 setup.py build_ext --inplace --rpath=$WDIR --library-dirs=$WDIR install --user
```
creates a broken module:
```
>>> from primecountpy import primecount
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dimpase/.local/lib/python3.9/site-packages/primecountpy-0.0.0-py3.9-linux-x86_64.egg/primecountpy/__init__.py", line 1, in <module>
    from .primecount import *
ModuleNotFoundError: No module named 'primecountpy.primecount'
```

**Comment by mkoeppe** [comment]
reorder `install` and `build_ext`

**Comment by dimpase** [comment]
same result.

**Comment by dimpase** [comment]
with this command (no matter in which order `install` and `build_ext` are), I see a weird `-Wl,--enable-new-dtags,-R/home/dimpase/tmp/lib`
instead of  `-Wl,-rpath,/home/dimpase/tmp/lib`

In full:
```
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-z,relro -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.9/primecountpy/primecount.o -L/home/dimpase/tmp/lib -Wl,--enable-new-dtags,-R/home/dimpase/tmp/lib -lprimesieve -lprimecount -o /home/dimpase/work/primecountpy/primecountpy/primecount.cpython-39-x86_64-linux-gnu.so
```
vs (good)
```
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-z,relro -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.9/primecountpy/primecount.o -L/home/dimpase/tmp/lib -lprimesieve -lprimecount -o build/lib.linux-x86_64-3.9/primecountpy/primecount.cpython-39-x86_64-linux-gnu.so -Wl,-rpath,/home/dimpase/tmp/lib
```

**Comment by mkoeppe** [comment]
You may want to change from `distutils.command.build_ext` to `setuptools.command.build_ext`

**Comment by dimpase** [comment]
not much luck with this either
```
$ python3 setup.py install --user build_ext --inplace --rpath=$WDIR --library-dirs=$WDIR
running install
running bdist_egg
running egg_info
creating primecountpy.egg-info
writing primecountpy.egg-info/PKG-INFO
writing dependency_links to primecountpy.egg-info/dependency_links.txt
writing requirements to primecountpy.egg-info/requires.txt
writing top-level names to primecountpy.egg-info/top_level.txt
writing manifest file 'primecountpy.egg-info/SOURCES.txt'
reading manifest file 'primecountpy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'AUTHORS'
writing manifest file 'primecountpy.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.9
creating build/lib.linux-x86_64-3.9/primecountpy
copying primecountpy/__init__.py -> build/lib.linux-x86_64-3.9/primecountpy
copying primecountpy/defs.pxd -> build/lib.linux-x86_64-3.9/primecountpy
running build_ext
Compiling primecountpy/primecount.pyx because it changed.
[1/1] Cythonizing primecountpy/primecount.pyx
building 'primecountpy.primecount' extension
creating build/temp.linux-x86_64-3.9
creating build/temp.linux-x86_64-3.9/primecountpy
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/lib/python3/dist-packages/cysignals -I/usr/include/python3.9 -c primecountpy/primecount.cpp -o build/temp.linux-x86_64-3.9/primecountpy/primecount.o
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-z,relro -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.9/primecountpy/primecount.o -L/home/dimpase/tmp/lib -Wl,--enable-new-dtags,-R/home/dimpase/tmp/lib -lprimesieve -lprimecount -o build/lib.linux-x86_64-3.9/primecountpy/primecount.cpython-39-x86_64-linux-gnu.so
Traceback (most recent call last):
  File "/home/dimpase/work/primecountpy/setup.py", line 32, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 23, in run
    self.build()
  File "/usr/lib/python3.9/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/dimpase/work/primecountpy/setup.py", line 13, in run
    du_build_ext.run(self)
  File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/usr/lib/python3/dist-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib/python3.9/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/usr/lib/python3/dist-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/usr/lib/python3.9/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.9/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 197, in build_extension
    if ext._needs_stub:
AttributeError: 'Extension' object has no attribute '_needs_stub'
```

**Comment by dimpase** [comment]
OK, switching to `pip` helps:
```
python3 -m pip install --no-clean -e . --prefix=~/.local --global-option=build_ext  --global-option="--library-dirs=$WDIR" --global-option="--rpath=$WDIR"
```
produces both `pytest`-able install, and something that actually works at command line.

**Comment by mkoeppe** [comment]
Try if you can use `--build-option` instead of `--global-option`

**Comment by dimpase** [comment]
I'm just getting `no such option: --build-option` this way.

**Comment by dimpase** [comment]
And on macOS, of course, one needs to `export DYLD_LIBRARY_PATH=$WDIR` for the result of this `pip3` contraption to work with `pytest`; whereas for interactive python session it's not enough, and I don't know what is.

**Comment by dimpase** [comment]
GH tests fail with
```
  [primecountpy-git]       File "setup.py", line 7, in run
  [primecountpy-git]         from Cython.Build.Dependencies import cythonize
  [primecountpy-git]     ModuleNotFoundError: No module named 'Cython'
  [primecountpy-git]     Building wheel for primecountpy (PEP 517): finished with status 'error'
  [primecountpy-git]     ERROR: Failed building wheel for primecountpy
```

 not sure why, Cython should not be missing

**Comment by mkoeppe** [comment]
The branch on ticket https://trac.sagemath.org/ticket/32894 does not have Cython in the `dependencies`

**Comment by dimpase** [comment]
hmm, there is an order only dependency on $(PYTHON_TOOLCHAIN)
So it should become a normal dependency, or is Cython now a separate
dependency?

**Comment by dimpase** [comment]
> The branch on ticket https://trac.sagemath.org/ticket/32894 does not have Cython in the `dependencies`

I don't even understand how this thing knows which Sage branch to take...

**Comment by mkoeppe** [comment]
> > The branch on ticket https://trac.sagemath.org/ticket/32894 does not have Cython in the `dependencies`
> 
> I don't even understand how this thing knows which Sage branch to take...

https://github.com/dimpase/primecountpy/blob/master/.github/workflows/ci-sage.yml#L55

**Comment by dimpase** [comment]
the latest iteration https://github.com/dimpase/primecountpy/actions/runs/1527216529 is failing again, with an unclear message in primecountpy-git (as often happens, the included in the logs part is too short to get any info - will the full log be eventually avaialble in artefacts?)

**Comment by mkoeppe** [comment]
Scroll down to the section "Print out logs for immediate inspection"

**Pull request merged**
